### ISSUE TITLE
The demo meow crashed

### ISSUE THREAD

**Issue by StudentWan** [jorendorff/es6-in-depth#6]
Hi Jason, sorry to bother you. The demo of talking cat seems crashed somehow.
I checked its source code and found out that ace.js&&jquery.min.js seems blocked.
Hope you can fix it if convenient.
BTW, you articles are amazing, thx a lot...

**Comment by StudentWan** [comment]
I downloaded the source code of this demo and changed its <script src>, and it worked!
Don't know if this problem is general or just because of I'm in China and blocked by the Wall, so still hope you can check out, thx

**Comment by jorendorff** [comment]
No, it was blocked by Content-Security-Policy. Thank you for reporting this! It should be fixed now. 😸

**Comment by StudentWan** [comment]
Thanks a lot!
